site_name: Fortlev Solar SDK
site_url: https://patrickpasquini.github.io/fortlev_solar_sdk/
site_author: Patrick Pasquini

nav:
  - Get Started: index.md
  - API Reference:
      - FortlevSolarClient: reference/fortlev_solar_client.md
  - Models:
      - Auth: models/auth.md
      - Surface: models/surface.md
      - Component: models/component.md
      - City: models/city.md
      - Financing: models/financing.md
      - Order: models/order.md
      - PvKit: models/pv_kit.md
      - PvKitComponent: models/pv_kit_component.md
      - StructuralInformation: models/structural_information.md
      - Layout: models/layout.md
  - Errors:
      - RequestError: errors/request_error.md


theme:
  name: material
  logo: public/logo.png
  favicon: public/logo.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Nunito
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
  - search
  - social

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/patrickpasquini/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/patrick-pasquini/

copyright: |
  &copy; 2024 <a href="https://github.com/patrickpasquini/"  target="_blank" rel="noopener">Patrick Pasquini</a>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list